site_name: UDProbe
site_description: Library for testing and measuring network loss and latency between distributed endpoints
site_url: https://udprobe.readthedocs.io/
repo_url: https://github.com/nsw3550/udprobe
repo_name: nsw3550/udprobe

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Architecture: architecture.md
  - API Reference: api/index.md

markdown_extensions:
  - attr_list
  - tables
